name: xmake build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:

      fail-fast: false
      
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [release]
        include:
          - os: windows-latest
          - os: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: setup xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: Xmake Config
      run: xmake f -p runner.os -m ${{ matrix.build_type }}

    - name: Xmake Build
      run: xmake
    
    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
